[colors]
background = '#1509158e'
black = '#150915'
blue = '#382667'
cursor = '#c4c1c4'
cyan = '#4B315F'
foreground = '#c4c1c4'
green = '#624D69'
magenta = '#856671'
red = '#5B3887'
tabs = '#c4c1c4'
tabs-active = '#6A5395'
white = '#c4c1c4'
yellow = '#c4c1c4'
dim-black = '#1509158e'
dim-blue = '#3826678e'
dim-cyan = '#4B315F8e'
dim-foreground = '#c4c1c48e'
dim-green = '#624D698e'
dim-magenta = '#8566718e'
dim-red = '#5B38878e'
dim-white = '#6A53958e'
dim-yellow = '#c4c1c48e'
light-black = '#382667'
light-blue = '#4B315F'
light-cyan = '#624D69'
light-foreground = '#856671'
light-green = '#5B3887'
light-magenta = '#6A5395'
light-red = '#c4c1c4'
light-white = '#382667'
light-yellow = '#4B315F'
