[colors]
background = '#0e13218e'
black = '#0e1321'
blue = '#4B4B54'
cursor = '#c2c4c7'
cyan = '#61606C'
foreground = '#c2c4c7'
green = '#3C5780'
magenta = '#727489'
red = '#80818E'
tabs = '#c2c4c7'
tabs-active = '#9896A4'
white = '#c2c4c7'
yellow = '#c2c4c7'
dim-black = '#0e13218e'
dim-blue = '#4B4B548e'
dim-cyan = '#61606C8e'
dim-foreground = '#c2c4c78e'
dim-green = '#3C57808e'
dim-magenta = '#7274898e'
dim-red = '#80818E8e'
dim-white = '#9896A48e'
dim-yellow = '#c2c4c78e'
light-black = '#4B4B54'
light-blue = '#61606C'
light-cyan = '#3C5780'
light-foreground = '#727489'
light-green = '#80818E'
light-magenta = '#9896A4'
light-red = '#c2c4c7'
light-white = '#4B4B54'
light-yellow = '#61606C'
