[colors.primary]
background = "#0e1321"
foreground = "#c2c4c7"

[colors.cursor]
text = "#0e1321"
cursor = "#c2c4c7"

[colors.vi_mode_cursor]
text = "#0e1321"
cursor = "#c2c4c7"

[colors.search.matches]
foreground = "#0e1321"
background = "#c2c4c7"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#5d6272"
background = "#c2c4c7"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#0e1321"
red = "#4B4B54"
green = "#61606C"
yellow = "#3C5780"
blue = "#727489"
magenta = "#80818E"
cyan = "#9896A4"
white = "#c2c4c7"

[colors.bright]
black = "#5d6272"
red = "#4B4B54"
green = "#61606C"
yellow = "#3C5780"
blue = "#727489"
magenta = "#80818E"
cyan = "#9896A4"
white = "#c2c4c7"

[colors.dim]
black = "#c2c4c7"
red = "#4B4B54"
green = "#80818E"
yellow = "#3C5780"
blue = "#727489"
magenta = "#61606C"
cyan = "#9896A4"
white = "#5d6272"

