[colors.primary]
background = "#150915"
foreground = "#c4c1c4"

[colors.cursor]
text = "#150915"
cursor = "#c4c1c4"

[colors.vi_mode_cursor]
text = "#150915"
cursor = "#c4c1c4"

[colors.search.matches]
foreground = "#150915"
background = "#c4c1c4"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#6c586c"
background = "#c4c1c4"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#150915"
red = "#382667"
green = "#4B315F"
yellow = "#624D69"
blue = "#856671"
magenta = "#5B3887"
cyan = "#6A5395"
white = "#c4c1c4"

[colors.bright]
black = "#6c586c"
red = "#382667"
green = "#4B315F"
yellow = "#624D69"
blue = "#856671"
magenta = "#5B3887"
cyan = "#6A5395"
white = "#c4c1c4"

[colors.dim]
black = "#c4c1c4"
red = "#382667"
green = "#5B3887"
yellow = "#624D69"
blue = "#856671"
magenta = "#4B315F"
cyan = "#6A5395"
white = "#6c586c"

